### ISSUE TITLE
Problem when executing npm run serve

### ISSUE THREAD

**Issue by antoniosv** [isaaclyman/Viano#2]
Hi!
I'm getting this error when trying to execute npm run serve:

`/home/jesus/repos/Viano/node_modules/@vue/cli-service/bin/vue-cli-service.js:4
const { error } = require('@vue/cli-shared-utils')
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3`

I'm running Linux Mint 18.2 Sonya, npm version 3.5.2. Any hints?

**Comment by isaaclyman** [comment]
Hey! What version of NPM and Node are you running?
`node --version`
`npm --version`

**Comment by antoniosv** [comment]
Running:
node v4.2.6
npm version 3.5.2

**Comment by isaaclyman** [comment]
Cool, looks like you're a few versions behind. Try updating Node to 8.0 or higher and NPM to 5.0 or higher and let me know if that helps.

**Comment by antoniosv** [comment]
Great! That worked =) 
After updating, I had to run  `npm rebuild node-sass --force` and `npm install`, and now it works. Thank you!
